# Generated by Django 5.2 on 2025-04-28 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ghluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='core.contact')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customfield')),
            ],
            options={
                'unique_together': {('contact', 'custom_field')},
            },
        ),
    ]
