# Generated by Django 5.2 on 2025-04-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='LocationId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='LocationId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
