# Generated by Django 5.2 on 2025-04-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ghluser'),
        ('opportunities', '0004_opportunity_locationid_pipeline_locationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='LocationId',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ghluser'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opp_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
