# Generated by Django 5.2 on 2025-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_remove_opportunity_locationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
