# Generated by Django 5.2 on 2025-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_alter_opportunity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='stage_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
