# Generated by Django 5.2 on 2025-04-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ghluser'),
        ('opportunities', '0008_pipelinestage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customfield')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='opportunities.opportunity')),
            ],
            options={
                'unique_together': {('opportunity', 'custom_field')},
            },
        ),
    ]
