# Generated by Django 5.2 on 2025-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_opportunitycustomfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitycustomfieldvalue',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
