# Generated by Django 5.2 on 2025-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0010_alter_opportunitycustomfieldvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
