# Generated by Django 5.2 on 2025-04-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0011_pipelinestage_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='stage_id',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='opportunities.pipelinestage'),
        ),
    ]
