# Generated by Django 5.2 on 2025-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_remove_opportunity_stage_id_opportunity_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
